In [56]:
import pandas as pd
from sklearn.datasets import make_classification,make_blobs,make_moons
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')


In [57]:
df=pd.read_csv('data/cleand_default_of_credit_card_clients.csv')

In [58]:
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2      0      0   
1     120000    2          2         2   26      0      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57      0      0      0      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  def_pay  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 24 columns]

In [59]:
## imbalance data set
df['def_pay'].unique()

array([1, 0])

In [60]:
df['PAY_1'].unique()

array([2, 0, 1, 3, 4, 8, 7, 5, 6])

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  30000 non-null  int64
 1   SEX        30000 non-null  int64
 2   EDUCATION  30000 non-null  int64
 3   MARRIAGE   30000 non-null  int64
 4   AGE        30000 non-null  int64
 5   PAY_1      30000 non-null  int64
 6   PAY_2      30000 non-null  int64
 7   PAY_3      30000 non-null  int64
 8   PAY_4      30000 non-null  int64
 9   PAY_5      30000 non-null  int64
 10  PAY_6      30000 non-null  int64
 11  BILL_AMT1  30000 non-null  int64
 12  BILL_AMT2  30000 non-null  int64
 13  BILL_AMT3  30000 non-null  int64
 14  BILL_AMT4  30000 non-null  int64
 15  BILL_AMT5  30000 non-null  int64
 16  BILL_AMT6  30000 non-null  int64
 17  PAY_AMT1   30000 non-null  int64
 18  PAY_AMT2   30000 non-null  int64
 19  PAY_AMT3   30000 non-null  int64
 20  PAY_AMT4   30000 non-null  int64
 21  PAY_AMT5   3

In [62]:
df['PAY_1'].value_counts()

PAY_1
0    23182
1     3688
2     2667
3      322
4       76
5       26
8       19
6       11
7        9
Name: count, dtype: int64

In [63]:
## Segregate the colum for scaledown

In [64]:
X=df.drop(['def_pay'],axis=1)

In [65]:
y=df[['def_pay']]

In [66]:
df['def_pay'].unique()

array([1, 0])

In [67]:
#X, y = make_moons(n_samples=1000, noise=0.7)

In [68]:
#X, y = make_moons(n_samples=1000, noise=0.7)
#plt.scatter(X[:,0],X[:,1],c=y)
#plt.show()

In [69]:
column=X.columns
print(column)

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')


In [70]:
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

In [71]:
numerical_pip=Pipeline(
    steps=[
        ('scaler',StandardScaler())
    ]
)

preprocessor=ColumnTransformer([
    ('numeric',numerical_pip,column)
])

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

In [74]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [75]:
X_train.shape

(21000, 23)

In [76]:
X_test.shape


(9000, 23)

In [77]:
pd.DataFrame(X_test,columns=preprocessor.get_feature_names_out())

numeric__LIMIT_BAL  numeric__SEX  numeric__EDUCATION  numeric__MARRIAGE  \
0              -1.139003     -1.231086            0.216565          -1.073440   
1               0.323213      0.812291            0.216565           0.845048   
2               1.862388     -1.231086           -1.127766           0.845048   
3               0.323213      0.812291           -1.127766           0.845048   
4               0.015378      0.812291           -1.127766           0.845048   
...                  ...           ...                 ...                ...   
8995            0.400172     -1.231086           -1.127766          -1.073440   
8996            1.246718      0.812291           -1.127766          -1.073440   
8997           -1.139003     -1.231086            0.216565           0.845048   
8998           -0.600292      0.812291            1.560897           0.845048   
8999            0.861924     -1.231086            0.216565           0.845048   

      numeric__AGE  numeric__PAY_1  numeric__PAY_2  numeric__PAY_3  \
0         0.164656       -0.468416       -0.396151       -0.382004   
1         1.034894        0.840008       -0.396151       -0.382004   
2        -0.923141       -0.468416       -0.396151       -0.382004   
3        -0.705581       -0.468416       -0.396151       -0.382004   
4         0.382216       -0.468416       -0.396151       -0.382004   
...            ...             ...             ...             ...   
8995      0.382216       -0.468416       -0.396151       -0.382004   
8996      0.382216       -0.468416       -0.396151       -0.382004   
8997     -0.379242       -0.468416       -0.396151       -0.382004   
8998     -1.358260       -0.468416       -0.396151       -0.382004   
8999      1.252453       -0.468416       -0.396151       -0.382004   

      numeric__PAY_4  numeric__PAY_5  ...  numeric__BILL_AMT3  \
0          -0.339993        2.506572  ...           -0.517827   
1          -0.339993       -0.308897  ...           -0.674425   
2          -0.339993       -0.308897  ...           -0.450088   
3          -0.339993       -0.308897  ...           -0.674468   
4          -0.339993       -0.308897  ...           -0.364491   
...              ...             ...  ...                 ...   
8995       -0.339993       -0.308897  ...           -0.497393   
8996       -0.339993       -0.308897  ...            0.014170   
8997       -0.339993       -0.308897  ...           -0.453093   
8998       -0.339993       -0.308897  ...           -0.361972   
8999       -0.339993       -0.308897  ...            0.449466   

      numeric__BILL_AMT4  numeric__BILL_AMT5  numeric__BILL_AMT6  \
0              -0.495906           -0.481219           -0.521625   
1              -0.671125           -0.662746           -0.652089   
2              -0.041830           -0.367911           -0.075875   
3              -0.671172           -0.652030           -0.620966   
4              -0.309084           -0.413231           -0.592753   
...                  ...                 ...                 ...   
8995           -0.599515           -0.602276           -0.665699   
8996            0.108582            0.193568            0.289392   
8997           -0.498982           -0.476405           -0.470936   
8998           -0.499697           -0.170871           -0.635501   
8999            0.309136            0.383536            0.425122   

      numeric__PAY_AMT1  numeric__PAY_AMT2  numeric__PAY_AMT3  \
0             -0.202513          -0.178393          -0.243247   
1             -0.333370          -0.237431          -0.284034   
2              0.603235           0.395304           1.882136   
3             -0.333370          -0.237431          -0.284034   
4             -0.041678          -0.040636           0.068238   
...                 ...                ...                ...   
8995          -0.215960          -0.119354          -0.230154   
8996          -0.100529          -0.119354          -0.122392   
8997     

In [78]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,recall_score

In [79]:
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
X_train, y_train = oversample.fit_resample(X_train, y_train)
print(y_train.value_counts())

def_pay
0          16300
1          16300
Name: count, dtype: int64


## logisticRegression

In [80]:
from sklearn.linear_model  import LogisticRegression

In [81]:
lg=LogisticRegression(penalty= 'l2',C=1.5)
lg.fit(X_train,y_train)
y_pred=lg.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.7765555555555556


In [82]:
#hyperparamater tuning
param={'penalty':["l1", "l2", "elasticnet"],
      'C':[1,1.5,1.0,12,6,10,0.1]
      }

In [83]:
from sklearn.model_selection import GridSearchCV

In [84]:
clf=GridSearchCV(estimator=lg,param_grid=param,cv=5)
clf.fit(X_train,y_train)
print(clf.best_estimator_)
print(clf.best_params_)
print(clf.best_score_)

LogisticRegression(C=0.1)
{'C': 0.1, 'penalty': 'l2'}
0.7060429447852761


In [85]:
y_pred1=clf.predict(X_test)

In [86]:
print(clf.best_estimator_)
print(clf.best_params_)
print(clf.best_score_)

LogisticRegression(C=0.1)
{'C': 0.1, 'penalty': 'l2'}
0.7060429447852761


## Randomforest

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
#X, y = make_classification(n_samples=1000, n_features=22,n_informative=2, n_redundant=0,random_state=0, shuffle=False)

In [89]:
randoms=RandomForestClassifier(criterion='gini',max_depth=4,n_estimators= 8)
randoms.fit(X_train,y_train)
y_preds=randoms.predict(X_test)
print(accuracy_score(y_test,y_preds))

print(confusion_matrix(y_test,y_preds))
print(classification_report(y_test,y_preds))

0.7775555555555556
[[5895 1169]
 [ 833 1103]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85      7064
           1       0.49      0.57      0.52      1936

    accuracy                           0.78      9000
   macro avg       0.68      0.70      0.69      9000
weighted avg       0.79      0.78      0.78      9000



In [90]:
param_r={'criterion':["gini","log_loss"],
      'max_depth':[2,5,7,3]
      }

In [91]:
from sklearn.svm import SVC

In [92]:
svs=SVC(gamma='auto')

In [93]:
svs.fit(X_train,y_train)

SVC(gamma='auto')

In [94]:
y_pred1=svs.predict(X_test)


In [95]:
print(accuracy_score(y_test,y_pred1))

0.7595555555555555


In [96]:
paramsss={
    'C':[1,2,3,4,5,6,7,8,9],
    'kernel':['rbf']
}

In [97]:
cfs=GridSearchCV(estimator=svs,param_grid=paramsss,cv=2)

In [98]:
cfs.fit(X_train,y_train)

GridSearchCV(cv=2, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9], 'kernel': ['rbf']})

In [99]:
cfs_pred=cfs.predict(X_test)

In [100]:
print(accuracy_score(y_test,cfs_pred))

0.7611111111111111


In [101]:
import optuna
import xgboost as xgb


In [102]:
import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection

def objective():
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)  # Prepare the data.
    
    clf = sklearn.ensemble.RandomForestClassifier(    
        n_estimators=13, max_depth=6)  # Define the model.
    
    return sklearn.model_selection.cross_val_score(
        clf, X, y, n_jobs=-1, cv=3).mean()  # Train and evaluate the model.

print('Accuracy: {}'.format(objective()))

/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Accuracy: 0.8151999999999999


In [103]:
import optuna

def objective(trial):

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)
    
    n_estimators = trial.suggest_int('n_estimators', 2, 20)
    max_depth = int(trial.suggest_float('max_depth', 1, 32, log=True))
    
    clf = sklearn.ensemble.RandomForestClassifier(
        n_estimators=n_estimators, max_depth=max_depth)
    
    return sklearn.model_selection.cross_val_score(
        clf, X,y, n_jobs=-1, cv=3).mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

trial = study.best_trial

print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))

[I 2023-07-24 17:27:54,311] A new study created in memory with name: no-name-cf261594-7b60-4a13-a1c8-5dc415cdb7b0
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel()

Accuracy: 0.8183666666666666
Best hyperparameters: {'n_estimators': 8, 'max_depth': 5.782567005258288}


In [104]:
import sklearn.svm

def objective(trial):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

    classifier = trial.suggest_categorical('classifier', ['RandomForest', 'SVC'])
    
    if classifier == 'RandomForest':
        n_estimators = trial.suggest_int('n_estimators', 2, 20)
        max_depth = int(trial.suggest_float('max_depth', 1, 32, log=True))

        clf = sklearn.ensemble.RandomForestClassifier(
            n_estimators=n_estimators, max_depth=max_depth)
    else:
        c = trial.suggest_float('svc_c', 1e-10, 1e10, log=True)
        
        clf = sklearn.svm.SVC(C=c, gamma='auto')

    return sklearn.model_selection.cross_val_score(
        clf, X, y, n_jobs=-1, cv=3).mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=5)

trial = study.best_trial

print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))

[I 2023-07-24 17:28:04,468] A new study created in memory with name: no-name-d877c855-2cca-4634-b70f-4e41354c9ba6
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/pratik/Downloads/Default-credit-card-client-main/env/lib/python3.8/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel()

Accuracy: 0.8091666666666667
Best hyperparameters: {'classifier': 'RandomForest', 'n_estimators': 20, 'max_depth': 29.720797008333278}


## randomforest give 81% accuracy

In [105]:
import pickle

def load_model_from_pickle(file_path):
    with open(file_path, 'rb') as file:
        model = pickle.load(file)
    return model

# Replace 'path_to_model.pkl' with the actual path to your 'model.pkl' file
model_path = 'model.pkl'
loaded_model = load_model_from_pickle(model_path)


FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'