In [1]:
import pandas as pd
from sklearn.datasets import make_classification,make_blobs,make_moons
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')


In [2]:
df=pd.read_csv('/home/pratik/Downloads/Default-credit-card-client-main/notebook/data/cleand_default_of_credit_card_clients.csv')

In [3]:
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2      0      0   
1     120000    2          2         2   26      0      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57      0      0      0      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  def_pay  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 24 columns]

In [4]:
## imbalance data set
df['def_pay'].unique()

array([1, 0])

In [5]:
df['PAY_1'].unique()

array([2, 0, 1, 3, 4, 8, 7, 5, 6])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  30000 non-null  int64
 1   SEX        30000 non-null  int64
 2   EDUCATION  30000 non-null  int64
 3   MARRIAGE   30000 non-null  int64
 4   AGE        30000 non-null  int64
 5   PAY_1      30000 non-null  int64
 6   PAY_2      30000 non-null  int64
 7   PAY_3      30000 non-null  int64
 8   PAY_4      30000 non-null  int64
 9   PAY_5      30000 non-null  int64
 10  PAY_6      30000 non-null  int64
 11  BILL_AMT1  30000 non-null  int64
 12  BILL_AMT2  30000 non-null  int64
 13  BILL_AMT3  30000 non-null  int64
 14  BILL_AMT4  30000 non-null  int64
 15  BILL_AMT5  30000 non-null  int64
 16  BILL_AMT6  30000 non-null  int64
 17  PAY_AMT1   30000 non-null  int64
 18  PAY_AMT2   30000 non-null  int64
 19  PAY_AMT3   30000 non-null  int64
 20  PAY_AMT4   30000 non-null  int64
 21  PAY_AMT5   3

In [7]:
df['PAY_1'].value_counts()

PAY_1
0    23182
1     3688
2     2667
3      322
4       76
5       26
8       19
6       11
7        9
Name: count, dtype: int64

In [8]:
## Segregate the colum for scaledown

In [9]:
X=df.drop(['def_pay'],axis=1)

In [10]:
y=df[['def_pay']]

In [11]:
#X, y = make_moons(n_samples=1000, noise=0.7)

In [12]:
#X, y = make_moons(n_samples=1000, noise=0.7)
#plt.scatter(X[:,0],X[:,1],c=y)
#plt.show()

In [13]:
column=X.columns
print(column)

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')


In [14]:
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

In [15]:
numerical_pip=Pipeline(
    steps=[
        ('scaler',StandardScaler())
    ]
)

preprocessor=ColumnTransformer([
    ('numeric',numerical_pip,column)
])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=30)

In [18]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [19]:
X_train.shape

(21000, 23)

In [20]:
X_test.shape


(9000, 23)

In [21]:
pd.DataFrame(X_test,columns=preprocessor.get_feature_names_out())

numeric__LIMIT_BAL  numeric__SEX  numeric__EDUCATION  numeric__MARRIAGE  \
0              -1.139003     -1.231086            0.216565          -1.073440   
1               0.323213      0.812291            0.216565           0.845048   
2               1.862388     -1.231086           -1.127766           0.845048   
3               0.323213      0.812291           -1.127766           0.845048   
4               0.015378      0.812291           -1.127766           0.845048   
...                  ...           ...                 ...                ...   
8995            0.400172     -1.231086           -1.127766          -1.073440   
8996            1.246718      0.812291           -1.127766          -1.073440   
8997           -1.139003     -1.231086            0.216565           0.845048   
8998           -0.600292      0.812291            1.560897           0.845048   
8999            0.861924     -1.231086            0.216565           0.845048   

      numeric__AGE  numeric__PAY_1  numeric__PAY_2  numeric__PAY_3  \
0         0.164656       -0.468416       -0.396151       -0.382004   
1         1.034894        0.840008       -0.396151       -0.382004   
2        -0.923141       -0.468416       -0.396151       -0.382004   
3        -0.705581       -0.468416       -0.396151       -0.382004   
4         0.382216       -0.468416       -0.396151       -0.382004   
...            ...             ...             ...             ...   
8995      0.382216       -0.468416       -0.396151       -0.382004   
8996      0.382216       -0.468416       -0.396151       -0.382004   
8997     -0.379242       -0.468416       -0.396151       -0.382004   
8998     -1.358260       -0.468416       -0.396151       -0.382004   
8999      1.252453       -0.468416       -0.396151       -0.382004   

      numeric__PAY_4  numeric__PAY_5  ...  numeric__BILL_AMT3  \
0          -0.339993        2.506572  ...           -0.517827   
1          -0.339993       -0.308897  ...           -0.674425   
2          -0.339993       -0.308897  ...           -0.450088   
3          -0.339993       -0.308897  ...           -0.674468   
4          -0.339993       -0.308897  ...           -0.364491   
...              ...             ...  ...                 ...   
8995       -0.339993       -0.308897  ...           -0.497393   
8996       -0.339993       -0.308897  ...            0.014170   
8997       -0.339993       -0.308897  ...           -0.453093   
8998       -0.339993       -0.308897  ...           -0.361972   
8999       -0.339993       -0.308897  ...            0.449466   

      numeric__BILL_AMT4  numeric__BILL_AMT5  numeric__BILL_AMT6  \
0              -0.495906           -0.481219           -0.521625   
1              -0.671125           -0.662746           -0.652089   
2              -0.041830           -0.367911           -0.075875   
3              -0.671172           -0.652030           -0.620966   
4              -0.309084           -0.413231           -0.592753   
...                  ...                 ...                 ...   
8995           -0.599515           -0.602276           -0.665699   
8996            0.108582            0.193568            0.289392   
8997           -0.498982           -0.476405           -0.470936   
8998           -0.499697           -0.170871           -0.635501   
8999            0.309136            0.383536            0.425122   

      numeric__PAY_AMT1  numeric__PAY_AMT2  numeric__PAY_AMT3  \
0             -0.202513          -0.178393          -0.243247   
1             -0.333370          -0.237431          -0.284034   
2              0.603235           0.395304           1.882136   
3             -0.333370          -0.237431          -0.284034   
4             -0.041678          -0.040636           0.068238   
...                 ...                ...                ...   
8995          -0.215960          -0.119354          -0.230154   
8996          -0.100529          -0.119354          -0.122392   
8997     

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,recall_score

## logisticRegression

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
logic=LogisticRegression()
logic.fit(X_train,y_train)

LogisticRegression()

In [25]:
y_pred=logic.predict(X_test)
logic_report=classification_report(y_test,y_pred)
confusion_report = confusion_matrix(y_test,y_pred)


In [26]:
print(logic_report)
print(confusion_report)
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7064
           1       0.66      0.33      0.44      1936

    accuracy                           0.82      9000
   macro avg       0.75      0.64      0.67      9000
weighted avg       0.80      0.82      0.80      9000

[[6734  330]
 [1290  646]]
0.82


In [27]:
print(confusion_matrix(y_test,y_pred))

[[6734  330]
 [1290  646]]


## RandomForestClassifier

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
randm=RandomForestClassifier()
randm.fit(X_train,y_train)

RandomForestClassifier()

In [30]:
y_pred=logic.predict(X_test)

In [31]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[6734  330]
 [1290  646]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7064
           1       0.66      0.33      0.44      1936

    accuracy                           0.82      9000
   macro avg       0.75      0.64      0.67      9000
weighted avg       0.80      0.82      0.80      9000

0.82


## hyperparameter tunning

In [32]:
param_grid = {'penalty':['l1','l2'], 'C' : [0.001, 0.01, 0.1, 1, 10, 100, 1000] }

In [33]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(estimator = logic , param_grid = param_grid, 
                   cv=5)
best_model = clf.fit(X_train, y_train)
print('Best Penalty:', best_model.best_estimator_.get_params() ['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])


Best Penalty: l2
Best C: 1


In [34]:
y_pred=best_model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[6734  330]
 [1290  646]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7064
           1       0.66      0.33      0.44      1936

    accuracy                           0.82      9000
   macro avg       0.75      0.64      0.67      9000
weighted avg       0.80      0.82      0.80      9000

0.82


##  imblearn for imbalance dataset

In [35]:
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
X_train, y_train = oversample.fit_resample(X_train, y_train)
print(y_train.value_counts())

def_pay
0          16300
1          16300
Name: count, dtype: int64


In [36]:
clf = GridSearchCV(estimator = logic , param_grid = param_grid,cv=5)
best_model = clf.fit(X_train, y_train)
print('Best Penalty:', best_model.best_estimator_.get_params() ['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])


Best Penalty: l2
Best C: 0.01


In [37]:
y_predic=best_model.predict(X_test)
print(confusion_matrix(y_test,y_predic))
print(classification_report(y_test,y_predic))
print(accuracy_score(y_test,y_predic))

[[5925 1139]
 [ 842 1094]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86      7064
           1       0.49      0.57      0.52      1936

    accuracy                           0.78      9000
   macro avg       0.68      0.70      0.69      9000
weighted avg       0.79      0.78      0.79      9000

0.7798888888888889


### logistic

In [38]:
logic=logic.fit(X_train,y_train)
y_predic=logic.predict(X_test)
print(confusion_matrix(y_test,y_predic))
print(classification_report(y_test,y_predic))
print(accuracy_score(y_test,y_predic))

[[5917 1147]
 [ 845 1091]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86      7064
           1       0.49      0.56      0.52      1936

    accuracy                           0.78      9000
   macro avg       0.68      0.70      0.69      9000
weighted avg       0.79      0.78      0.78      9000

0.7786666666666666


### randomforest classification

In [39]:
randm=randm.fit(X_train,y_train)
y_predic=randm.predict(X_test)
print(confusion_matrix(y_test,y_predic))
print(classification_report(y_test,y_predic))
print(accuracy_score(y_test,y_predic))

[[6185  879]
 [ 995  941]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      7064
           1       0.52      0.49      0.50      1936

    accuracy                           0.79      9000
   macro avg       0.69      0.68      0.68      9000
weighted avg       0.79      0.79      0.79      9000

0.7917777777777778


In [40]:
#as we seen the result there is no such improvments

In [41]:
from sklearn.svm import SVC

In [ ]:
#X_train, y_train = make_moons(n_samples=1000, noise=0.7)
#plt.scatter(X_train[:,0],X_train[:,1],c=y_train)
#plt.show()

In [ ]:
svc=SVC()
svc.fit(X_train,y_train)

In [44]:
y_predic=svc.predict(X_test)
print(confusion_matrix(y_test,y_predic))
print(classification_report(y_test,y_predic))
print(accuracy_score(y_test,y_predic))

[[5711 1353]
 [ 791 1145]]
              precision    recall  f1-score   support

           0       0.88      0.81      0.84      7064
           1       0.46      0.59      0.52      1936

    accuracy                           0.76      9000
   macro avg       0.67      0.70      0.68      9000
weighted avg       0.79      0.76      0.77      9000

0.7617777777777778


In [42]:
param_grids = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [ ]:
clfs=GridSearchCV(estimator=svc,param_grid=param_grids,cv=5)
model=clfs.fit(X_train,y_train)

In [ ]:
print(clf.best_params_)
print(clf.best_estimator_)


In [ ]:
y_predic=model.predict(X_test)
print(confusion_matrix(y_test,y_predic))
print(classification_report(y_test,y_predic))
print(accuracy_score(y_test,y_predic))